# Generated by Django 5.0 on 2024-01-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyra_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bestsellers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actual_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('quantity', models.BigIntegerField()),
            ],
        ),
    ]
