# Generated by Django 5.0 on 2024-01-30 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyra_app', '0002_bestsellers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='image',
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('actual_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(null=True, upload_to='images')),
                ('quantity', models.BigIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kyra_app.categories')),
            ],
        ),
    ]
